"""add generic warehouse models and manufacturing star schema

Revision ID: 1e6727a743f1
Revises: 'c89db66c2ac6'
Create Date: 2026-08-14 02:48:12.987134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6727a743f1'
down_revision: Union[str, None] = 'c89db66c2ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_machine',
    sa.Column('machine_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('machine_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('machine_key')
    )
    op.create_index(op.f('ix_dim_machine_machine_id'), 'dim_machine', ['machine_id'], unique=False)
    op.create_index(op.f('ix_dim_machine_machine_key'), 'dim_machine', ['machine_key'], unique=False)
    op.create_table('dim_plant',
    sa.Column('plant_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.String(), nullable=False),
    sa.Column('plant_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('plant_key')
    )
    op.create_index(op.f('ix_dim_plant_plant_id'), 'dim_plant', ['plant_id'], unique=False)
    op.create_index(op.f('ix_dim_plant_plant_key'), 'dim_plant', ['plant_key'], unique=False)
    op.create_table('fact_production',
    sa.Column('production_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('production_id', sa.String(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('machine_key', sa.Integer(), nullable=False),
    sa.Column('plant_key', sa.Integer(), nullable=False),
    sa.Column('units_produced', sa.Integer(), nullable=False),
    sa.Column('defect_count', sa.Integer(), nullable=False),
    sa.Column('operating_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['machine_key'], ['dim_machine.machine_key'], ),
    sa.ForeignKeyConstraint(['plant_key'], ['dim_plant.plant_key'], ),
    sa.PrimaryKeyConstraint('production_key')
    )
    op.create_index(op.f('ix_fact_production_date_key'), 'fact_production', ['date_key'], unique=False)
    op.create_index(op.f('ix_fact_production_machine_key'), 'fact_production', ['machine_key'], unique=False)
    op.create_index(op.f('ix_fact_production_plant_key'), 'fact_production', ['plant_key'], unique=False)
    op.create_index(op.f('ix_fact_production_production_id'), 'fact_production', ['production_id'], unique=False)
    op.create_index(op.f('ix_fact_production_production_key'), 'fact_production', ['production_key'], unique=False)
    op.create_table('warehouse_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_models_id'), 'warehouse_models', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_models_organization_id'), 'warehouse_models', ['organization_id'], unique=False)
    op.create_index(op.f('ix_warehouse_models_slug'), 'warehouse_models', ['slug'], unique=False)
    op.create_table('warehouse_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_model_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('table_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('grain', sa.String(), nullable=True),
    sa.Column('primary_keys', sa.JSON(), nullable=False),
    sa.Column('foreign_keys', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_model_id'], ['warehouse_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_tables_id'), 'warehouse_tables', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_tables_table_name'), 'warehouse_tables', ['table_name'], unique=False)
    op.create_index(op.f('ix_warehouse_tables_warehouse_model_id'), 'warehouse_tables', ['warehouse_model_id'], unique=False)
    pass
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_executions', sa.Column('celery_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_pipeline_executions_celery_task_id'), 'pipeline_executions', ['celery_task_id'], unique=False)
    op.create_table('M7',
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('sales_dirty_clean_output',
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('transformed_dataset',
    sa.Column('Sl. No', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Email ID', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('First Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Last Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('College Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Year of Passing', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Degree ', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Branch ', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('target_sales_orders',
    sa.Column('item', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('M5',
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('target_table',
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Total_revenue', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_warehouse_tables_warehouse_model_id'), table_name='warehouse_tables')
    op.drop_index(op.f('ix_warehouse_tables_table_name'), table_name='warehouse_tables')
    op.drop_index(op.f('ix_warehouse_tables_id'), table_name='warehouse_tables')
    op.drop_table('warehouse_tables')
    op.drop_index(op.f('ix_warehouse_models_slug'), table_name='warehouse_models')
    op.drop_index(op.f('ix_warehouse_models_organization_id'), table_name='warehouse_models')
    op.drop_index(op.f('ix_warehouse_models_id'), table_name='warehouse_models')
    op.drop_table('warehouse_models')
    op.drop_index(op.f('ix_fact_production_production_key'), table_name='fact_production')
    op.drop_index(op.f('ix_fact_production_production_id'), table_name='fact_production')
    op.drop_index(op.f('ix_fact_production_plant_key'), table_name='fact_production')
    op.drop_index(op.f('ix_fact_production_machine_key'), table_name='fact_production')
    op.drop_index(op.f('ix_fact_production_date_key'), table_name='fact_production')
    op.drop_table('fact_production')
    op.drop_index(op.f('ix_dim_plant_plant_key'), table_name='dim_plant')
    op.drop_index(op.f('ix_dim_plant_plant_id'), table_name='dim_plant')
    op.drop_table('dim_plant')
    op.drop_index(op.f('ix_dim_machine_machine_key'), table_name='dim_machine')
    op.drop_index(op.f('ix_dim_machine_machine_id'), table_name='dim_machine')
    op.drop_table('dim_machine')
    # ### end Alembic commands ###
