"""Add data_profiles table

Revision ID: 24d1a80fac3d
Revises: 'b06cb23208c9'
Create Date: 2026-08-08 15:55:02.201042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d1a80fac3d'
down_revision: Union[str, None] = 'b06cb23208c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('column_profiles', sa.JSON(), nullable=False),
    sa.Column('quality_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_profiles_data_source_id'), 'data_profiles', ['data_source_id'], unique=True)
    op.create_index(op.f('ix_data_profiles_id'), 'data_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_data_profiles_organization_id'), 'data_profiles', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_profiles_organization_id'), table_name='data_profiles')
    op.drop_index(op.f('ix_data_profiles_id'), table_name='data_profiles')
    op.drop_index(op.f('ix_data_profiles_data_source_id'), table_name='data_profiles')
    op.drop_table('data_profiles')
    # ### end Alembic commands ###
