"""Add pipelines and pipeline_executions tables

Revision ID: 48599b19c8b4
Revises: '24d1a80fac3d'
Create Date: 2026-08-08 16:13:19.344841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48599b19c8b4'
down_revision: Union[str, None] = '24d1a80fac3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('destination_config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_pipelines_organization_id'), 'pipelines', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pipelines_source_id'), 'pipelines', ['source_id'], unique=False)
    op.create_table('pipeline_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('records_read', sa.Integer(), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('logs', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_executions_id'), 'pipeline_executions', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_executions_organization_id'), 'pipeline_executions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pipeline_executions_pipeline_id'), 'pipeline_executions', ['pipeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_executions_pipeline_id'), table_name='pipeline_executions')
    op.drop_index(op.f('ix_pipeline_executions_organization_id'), table_name='pipeline_executions')
    op.drop_index(op.f('ix_pipeline_executions_id'), table_name='pipeline_executions')
    op.drop_table('pipeline_executions')
    op.drop_index(op.f('ix_pipelines_source_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_organization_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
