"""Add dag_nodes and dag_edges to pipelines table

Revision ID: 85b0e57ada67
Revises: '8ee73183872a'
Create Date: 2026-08-08 17:06:53.734653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b0e57ada67'
down_revision: Union[str, None] = '8ee73183872a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DROP TABLE IF EXISTS target_sales_orders CASCADE")
    op.add_column('pipelines', sa.Column('dag_nodes', sa.JSON(), nullable=True))
    op.add_column('pipelines', sa.Column('dag_edges', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'dag_edges')
    op.drop_column('pipelines', 'dag_nodes')
    op.create_table('target_sales_orders',
    sa.Column('item', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
