"""Add star schema warehouse tables

Revision ID: 8ee73183872a
Revises: '48599b19c8b4'
Create Date: 2026-08-08 16:32:32.261061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee73183872a'
down_revision: Union[str, None] = '48599b19c8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_customer',
    sa.Column('customer_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('customer_key')
    )
    op.create_index(op.f('ix_dim_customer_customer_id'), 'dim_customer', ['customer_id'], unique=False)
    op.create_index(op.f('ix_dim_customer_customer_key'), 'dim_customer', ['customer_key'], unique=False)
    op.create_index(op.f('ix_dim_customer_is_current'), 'dim_customer', ['is_current'], unique=False)
    op.create_table('dim_date',
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('date_key')
    )
    op.create_index(op.f('ix_dim_date_date_key'), 'dim_date', ['date_key'], unique=False)
    op.create_index(op.f('ix_dim_date_full_date'), 'dim_date', ['full_date'], unique=True)
    op.create_table('dim_location',
    sa.Column('location_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('location_key')
    )
    op.create_index(op.f('ix_dim_location_city'), 'dim_location', ['city'], unique=False)
    op.create_index(op.f('ix_dim_location_location_key'), 'dim_location', ['location_key'], unique=False)
    op.create_table('dim_product',
    sa.Column('product_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('product_key')
    )
    op.create_index(op.f('ix_dim_product_product_id'), 'dim_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_dim_product_product_key'), 'dim_product', ['product_key'], unique=False)
    op.create_table('fact_sales',
    sa.Column('sale_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('customer_key', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('location_key', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['customer_key'], ['dim_customer.customer_key'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['location_key'], ['dim_location.location_key'], ),
    sa.ForeignKeyConstraint(['product_key'], ['dim_product.product_key'], ),
    sa.PrimaryKeyConstraint('sale_key')
    )
    op.create_index(op.f('ix_fact_sales_customer_key'), 'fact_sales', ['customer_key'], unique=False)
    op.create_index(op.f('ix_fact_sales_date_key'), 'fact_sales', ['date_key'], unique=False)
    op.create_index(op.f('ix_fact_sales_location_key'), 'fact_sales', ['location_key'], unique=False)
    op.create_index(op.f('ix_fact_sales_order_id'), 'fact_sales', ['order_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_product_key'), 'fact_sales', ['product_key'], unique=False)
    op.execute("DROP TABLE IF EXISTS target_sales_orders CASCADE")
    op.execute("DROP TABLE IF EXISTS transformed_dataset CASCADE")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformed_dataset',
    sa.Column('Sl. No', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Email ID', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('First Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Last Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('College Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Year of Passing', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Degree ', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Branch ', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('target_sales_orders',
    sa.Column('item', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_fact_sales_sale_key'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_product_key'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_order_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_location_key'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_date_key'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_customer_key'), table_name='fact_sales')
    op.drop_table('fact_sales')
    op.drop_index(op.f('ix_dim_product_product_key'), table_name='dim_product')
    op.drop_index(op.f('ix_dim_product_product_id'), table_name='dim_product')
    op.drop_table('dim_product')
    op.drop_index(op.f('ix_dim_location_location_key'), table_name='dim_location')
    op.drop_index(op.f('ix_dim_location_city'), table_name='dim_location')
    op.drop_table('dim_location')
    op.drop_index(op.f('ix_dim_date_full_date'), table_name='dim_date')
    op.drop_index(op.f('ix_dim_date_date_key'), table_name='dim_date')
    op.drop_table('dim_date')
    op.drop_index(op.f('ix_dim_customer_is_current'), table_name='dim_customer')
    op.drop_index(op.f('ix_dim_customer_customer_key'), table_name='dim_customer')
    op.drop_index(op.f('ix_dim_customer_customer_id'), table_name='dim_customer')
    op.drop_table('dim_customer')
    # ### end Alembic commands ###
