"""Add organizations users and projects tables

Revision ID: a87d79aa867c
Revises: '6d8bf17e0aff'
Create Date: 2026-08-08 14:54:46.867404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87d79aa867c'
down_revision: Union[str, None] = '6d8bf17e0aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_projects_org'), table_name='projects')
    op.drop_index(op.f('idx_users_org_role'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_org_role'), 'users', ['organization_id', 'role'], unique=False)
    op.create_index(op.f('idx_projects_org'), 'projects', ['organization_id'], unique=False)
    # ### end Alembic commands ###
