"""add celery_task_id to pipeline_executions

Revision ID: c89db66c2ac6
Revises: 'cd40f916e4b6'
Create Date: 2026-08-08 18:42:59.762099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89db66c2ac6'
down_revision: Union[str, None] = 'cd40f916e4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS transformed_dataset CASCADE")
    op.execute("DROP TABLE IF EXISTS M5 CASCADE")
    op.execute("DROP TABLE IF EXISTS target_table CASCADE")
    op.execute("DROP TABLE IF EXISTS sales_dirty_clean_output CASCADE")
    op.execute("DROP TABLE IF EXISTS target_sales_orders CASCADE")
    op.execute("DROP TABLE IF EXISTS M7 CASCADE")

    op.add_column('pipeline_executions', sa.Column('celery_task_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_pipeline_executions_celery_task_id'), 'pipeline_executions', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_executions_celery_task_id'), table_name='pipeline_executions')
    op.drop_column('pipeline_executions', 'celery_task_id')
    op.create_table('M7',
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('target_sales_orders',
    sa.Column('item', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('sales_dirty_clean_output',
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('target_table',
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Total_revenue', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('M5',
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('transformed_dataset',
    sa.Column('Sl. No', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Email ID', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('First Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Last Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('College Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Year of Passing', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Degree ', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Branch ', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
